//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitChildPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEGZERSIZ
    {
        public int ID { get; set; }
        public string EgzersizAdi { get; set; }
        public string EgzersizResim { get; set; }
        public string EgzersizFayda { get; set; }
        public string EgzersizSeviye { get; set; }
        public string EgzersizYapilisi { get; set; }
    }
}
