//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitChildPanel.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLONERI
    {
        public int ID { get; set; }
        public string OneriAdi { get; set; }
        public string OneriResim { get; set; }
        public string OneriFayda { get; set; }
        public string OneriTavsiye { get; set; }
        public string OneriCalisanBolge { get; set; }
        public Nullable<System.DateTime> OneriEklenmeTarih { get; set; }
    }
}
